export const plants = [
  { plant_id: 1, plant_name: "Alpha Chemicals", is_active: true },
  { plant_id: 2, plant_name: "Beta Refinery", is_active: false },
  { plant_id: 3, plant_name: "Gamma Paints", is_active: true },
  { plant_id: 4, plant_name: "Delta Manufacturing", is_active: true },
  { plant_id: 5, plant_name: "Epsilon Textiles", is_active: false },
  { plant_id: 6, plant_name: "Zeta Engineering", is_active: true },
  { plant_id: 7, plant_name: "Eta Packaging", is_active: true },
  { plant_id: 8, plant_name: "Theta Steel Works", is_active: false },
  { plant_id: 9, plant_name: "Iota Lubricants", is_active: true },
  { plant_id: 10, plant_name: "Kappa Pharma", is_active: true },
  { plant_id: 11, plant_name: "Alpha Chemicals", is_active: true },
  { plant_id: 12, plant_name: "Beta Refinery", is_active: false },
  { plant_id: 13, plant_name: "Gamma Paints", is_active: true },
  { plant_id: 14, plant_name: "Delta Manufacturing", is_active: true },
  { plant_id: 15, plant_name: "Epsilon Textiles", is_active: false },
  { plant_id: 16, plant_name: "Zeta Engineering", is_active: true },
  { plant_id: 17, plant_name: "Eta Packaging", is_active: true },
  { plant_id: 18, plant_name: "Theta Steel Works", is_active: false },
  { plant_id: 19, plant_name: "Iota Lubricants", is_active: true },
  { plant_id: 20, plant_name: "Kappa Pharma", is_active: true },
  { plant_id: 21, plant_name: "Kappa Pharma", is_active: true },
];
